// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package sqlboiler

import (
	"bytes"
	"database/sql/driver"
	"encoding/json"
	"strconv"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/null/v8/convert"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// M type is for providing columns and column values to UpdateAll.
type M map[string]any

// ErrSyncFail occurs during insert when the record could not be retrieved in
// order to populate default value information. This usually happens when LastInsertId
// fails or there was a primary key configuration that was not resolvable.
var ErrSyncFail = errors.New("sqlboiler: failed to synchronize data after insert")

type insertCache struct {
	query        string
	retQuery     string
	valueMapping []uint64
	retMapping   []uint64
}

type updateCache struct {
	query        string
	valueMapping []uint64
}

func makeCacheKey(cols boil.Columns, nzDefaults []string) string {
	buf := strmangle.GetBuffer()

	buf.WriteString(strconv.Itoa(cols.Kind))
	for _, w := range cols.Cols {
		buf.WriteString(w)
	}

	if len(nzDefaults) != 0 {
		buf.WriteByte('.')
	}
	for _, nz := range nzDefaults {
		buf.WriteString(nz)
	}

	str := buf.String()
	strmangle.PutBuffer(buf)
	return str
}

type CampaignStatus string

// Enum values for CampaignStatus
const (
	CampaignStatusACTIVE   CampaignStatus = "ACTIVE"
	CampaignStatusINACTIVE CampaignStatus = "INACTIVE"
	CampaignStatusARCHIVED CampaignStatus = "ARCHIVED"
)

func AllCampaignStatus() []CampaignStatus {
	return []CampaignStatus{
		CampaignStatusACTIVE,
		CampaignStatusINACTIVE,
		CampaignStatusARCHIVED,
	}
}

func (e CampaignStatus) IsValid() error {
	switch e {
	case CampaignStatusACTIVE, CampaignStatusINACTIVE, CampaignStatusARCHIVED:
		return nil
	default:
		return errors.New("enum is not valid")
	}
}

func (e CampaignStatus) String() string {
	return string(e)
}

func (e CampaignStatus) Ordinal() int {
	switch e {
	case CampaignStatusACTIVE:
		return 0
	case CampaignStatusINACTIVE:
		return 1
	case CampaignStatusARCHIVED:
		return 2

	default:
		panic(errors.New("enum is not valid"))
	}
}

type EntityType string

// Enum values for EntityType
const (
	EntityTypeProduct    EntityType = "product"
	EntityTypeCampaign   EntityType = "campaign"
	EntityTypeService    EntityType = "service"
	EntityTypeCompetitor EntityType = "competitor"
	EntityTypeTopic      EntityType = "topic"
)

func AllEntityType() []EntityType {
	return []EntityType{
		EntityTypeProduct,
		EntityTypeCampaign,
		EntityTypeService,
		EntityTypeCompetitor,
		EntityTypeTopic,
	}
}

func (e EntityType) IsValid() error {
	switch e {
	case EntityTypeProduct, EntityTypeCampaign, EntityTypeService, EntityTypeCompetitor, EntityTypeTopic:
		return nil
	default:
		return errors.New("enum is not valid")
	}
}

func (e EntityType) String() string {
	return string(e)
}

func (e EntityType) Ordinal() int {
	switch e {
	case EntityTypeProduct:
		return 0
	case EntityTypeCampaign:
		return 1
	case EntityTypeService:
		return 2
	case EntityTypeCompetitor:
		return 3
	case EntityTypeTopic:
		return 4

	default:
		panic(errors.New("enum is not valid"))
	}
}

type ProjectStatus string

// Enum values for ProjectStatus
const (
	ProjectStatusACTIVE   ProjectStatus = "ACTIVE"
	ProjectStatusPAUSED   ProjectStatus = "PAUSED"
	ProjectStatusARCHIVED ProjectStatus = "ARCHIVED"
)

func AllProjectStatus() []ProjectStatus {
	return []ProjectStatus{
		ProjectStatusACTIVE,
		ProjectStatusPAUSED,
		ProjectStatusARCHIVED,
	}
}

func (e ProjectStatus) IsValid() error {
	switch e {
	case ProjectStatusACTIVE, ProjectStatusPAUSED, ProjectStatusARCHIVED:
		return nil
	default:
		return errors.New("enum is not valid")
	}
}

func (e ProjectStatus) String() string {
	return string(e)
}

func (e ProjectStatus) Ordinal() int {
	switch e {
	case ProjectStatusACTIVE:
		return 0
	case ProjectStatusPAUSED:
		return 1
	case ProjectStatusARCHIVED:
		return 2

	default:
		panic(errors.New("enum is not valid"))
	}
}

type ProjectConfigStatus string

// Enum values for ProjectConfigStatus
const (
	ProjectConfigStatusDRAFT           ProjectConfigStatus = "DRAFT"
	ProjectConfigStatusCONFIGURING     ProjectConfigStatus = "CONFIGURING"
	ProjectConfigStatusONBOARDING      ProjectConfigStatus = "ONBOARDING"
	ProjectConfigStatusONBOARDING_DONE ProjectConfigStatus = "ONBOARDING_DONE"
	ProjectConfigStatusDRYRUN_RUNNING  ProjectConfigStatus = "DRYRUN_RUNNING"
	ProjectConfigStatusDRYRUN_SUCCESS  ProjectConfigStatus = "DRYRUN_SUCCESS"
	ProjectConfigStatusDRYRUN_FAILED   ProjectConfigStatus = "DRYRUN_FAILED"
	ProjectConfigStatusACTIVE          ProjectConfigStatus = "ACTIVE"
	ProjectConfigStatusERROR           ProjectConfigStatus = "ERROR"
)

func AllProjectConfigStatus() []ProjectConfigStatus {
	return []ProjectConfigStatus{
		ProjectConfigStatusDRAFT,
		ProjectConfigStatusCONFIGURING,
		ProjectConfigStatusONBOARDING,
		ProjectConfigStatusONBOARDING_DONE,
		ProjectConfigStatusDRYRUN_RUNNING,
		ProjectConfigStatusDRYRUN_SUCCESS,
		ProjectConfigStatusDRYRUN_FAILED,
		ProjectConfigStatusACTIVE,
		ProjectConfigStatusERROR,
	}
}

func (e ProjectConfigStatus) IsValid() error {
	switch e {
	case ProjectConfigStatusDRAFT, ProjectConfigStatusCONFIGURING, ProjectConfigStatusONBOARDING, ProjectConfigStatusONBOARDING_DONE, ProjectConfigStatusDRYRUN_RUNNING, ProjectConfigStatusDRYRUN_SUCCESS, ProjectConfigStatusDRYRUN_FAILED, ProjectConfigStatusACTIVE, ProjectConfigStatusERROR:
		return nil
	default:
		return errors.New("enum is not valid")
	}
}

func (e ProjectConfigStatus) String() string {
	return string(e)
}

func (e ProjectConfigStatus) Ordinal() int {
	switch e {
	case ProjectConfigStatusDRAFT:
		return 0
	case ProjectConfigStatusCONFIGURING:
		return 1
	case ProjectConfigStatusONBOARDING:
		return 2
	case ProjectConfigStatusONBOARDING_DONE:
		return 3
	case ProjectConfigStatusDRYRUN_RUNNING:
		return 4
	case ProjectConfigStatusDRYRUN_SUCCESS:
		return 5
	case ProjectConfigStatusDRYRUN_FAILED:
		return 6
	case ProjectConfigStatusACTIVE:
		return 7
	case ProjectConfigStatusERROR:
		return 8

	default:
		panic(errors.New("enum is not valid"))
	}
}

// NullProjectConfigStatus is a nullable ProjectConfigStatus enum type. It supports SQL and JSON serialization.
type NullProjectConfigStatus struct {
	Val   ProjectConfigStatus
	Valid bool
}

// NullProjectConfigStatusFrom creates a new ProjectConfigStatus that will never be blank.
func NullProjectConfigStatusFrom(v ProjectConfigStatus) NullProjectConfigStatus {
	return NewNullProjectConfigStatus(v, true)
}

// NullProjectConfigStatusFromPtr creates a new NullProjectConfigStatus that be null if s is nil.
func NullProjectConfigStatusFromPtr(v *ProjectConfigStatus) NullProjectConfigStatus {
	if v == nil {
		return NewNullProjectConfigStatus("", false)
	}
	return NewNullProjectConfigStatus(*v, true)
}

// NewNullProjectConfigStatus creates a new NullProjectConfigStatus
func NewNullProjectConfigStatus(v ProjectConfigStatus, valid bool) NullProjectConfigStatus {
	return NullProjectConfigStatus{
		Val:   v,
		Valid: valid,
	}
}

// UnmarshalJSON implements json.Unmarshaler.
func (e *NullProjectConfigStatus) UnmarshalJSON(data []byte) error {
	if bytes.Equal(data, null.NullBytes) {
		e.Val = ""
		e.Valid = false
		return nil
	}

	if err := json.Unmarshal(data, &e.Val); err != nil {
		return err
	}

	e.Valid = true
	return nil
}

// MarshalJSON implements json.Marshaler.
func (e NullProjectConfigStatus) MarshalJSON() ([]byte, error) {
	if !e.Valid {
		return null.NullBytes, nil
	}
	return json.Marshal(e.Val)
}

// MarshalText implements encoding.TextMarshaler.
func (e NullProjectConfigStatus) MarshalText() ([]byte, error) {
	if !e.Valid {
		return []byte{}, nil
	}
	return []byte(e.Val), nil
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (e *NullProjectConfigStatus) UnmarshalText(text []byte) error {
	if text == nil || len(text) == 0 {
		e.Valid = false
		return nil
	}

	e.Val = ProjectConfigStatus(text)
	e.Valid = true
	return nil
}

// SetValid changes this NullProjectConfigStatus value and also sets it to be non-null.
func (e *NullProjectConfigStatus) SetValid(v ProjectConfigStatus) {
	e.Val = v
	e.Valid = true
}

// Ptr returns a pointer to this NullProjectConfigStatus value, or a nil pointer if this NullProjectConfigStatus is null.
func (e NullProjectConfigStatus) Ptr() *ProjectConfigStatus {
	if !e.Valid {
		return nil
	}
	return &e.Val
}

// IsZero returns true for null types.
func (e NullProjectConfigStatus) IsZero() bool {
	return !e.Valid
}

// Scan implements the Scanner interface.
func (e *NullProjectConfigStatus) Scan(value any) error {
	if value == nil {
		e.Val, e.Valid = "", false
		return nil
	}
	e.Valid = true
	return convert.ConvertAssign((*string)(&e.Val), value)
}

// Value implements the driver Valuer interface.
func (e NullProjectConfigStatus) Value() (driver.Value, error) {
	if !e.Valid {
		return nil, nil
	}
	return string(e.Val), nil
}

type CrisisStatus string

// Enum values for CrisisStatus
const (
	CrisisStatusNORMAL   CrisisStatus = "NORMAL"
	CrisisStatusWARNING  CrisisStatus = "WARNING"
	CrisisStatusCRITICAL CrisisStatus = "CRITICAL"
)

func AllCrisisStatus() []CrisisStatus {
	return []CrisisStatus{
		CrisisStatusNORMAL,
		CrisisStatusWARNING,
		CrisisStatusCRITICAL,
	}
}

func (e CrisisStatus) IsValid() error {
	switch e {
	case CrisisStatusNORMAL, CrisisStatusWARNING, CrisisStatusCRITICAL:
		return nil
	default:
		return errors.New("enum is not valid")
	}
}

func (e CrisisStatus) String() string {
	return string(e)
}

func (e CrisisStatus) Ordinal() int {
	switch e {
	case CrisisStatusNORMAL:
		return 0
	case CrisisStatusWARNING:
		return 1
	case CrisisStatusCRITICAL:
		return 2

	default:
		panic(errors.New("enum is not valid"))
	}
}

// NullCrisisStatus is a nullable CrisisStatus enum type. It supports SQL and JSON serialization.
type NullCrisisStatus struct {
	Val   CrisisStatus
	Valid bool
}

// NullCrisisStatusFrom creates a new CrisisStatus that will never be blank.
func NullCrisisStatusFrom(v CrisisStatus) NullCrisisStatus {
	return NewNullCrisisStatus(v, true)
}

// NullCrisisStatusFromPtr creates a new NullCrisisStatus that be null if s is nil.
func NullCrisisStatusFromPtr(v *CrisisStatus) NullCrisisStatus {
	if v == nil {
		return NewNullCrisisStatus("", false)
	}
	return NewNullCrisisStatus(*v, true)
}

// NewNullCrisisStatus creates a new NullCrisisStatus
func NewNullCrisisStatus(v CrisisStatus, valid bool) NullCrisisStatus {
	return NullCrisisStatus{
		Val:   v,
		Valid: valid,
	}
}

// UnmarshalJSON implements json.Unmarshaler.
func (e *NullCrisisStatus) UnmarshalJSON(data []byte) error {
	if bytes.Equal(data, null.NullBytes) {
		e.Val = ""
		e.Valid = false
		return nil
	}

	if err := json.Unmarshal(data, &e.Val); err != nil {
		return err
	}

	e.Valid = true
	return nil
}

// MarshalJSON implements json.Marshaler.
func (e NullCrisisStatus) MarshalJSON() ([]byte, error) {
	if !e.Valid {
		return null.NullBytes, nil
	}
	return json.Marshal(e.Val)
}

// MarshalText implements encoding.TextMarshaler.
func (e NullCrisisStatus) MarshalText() ([]byte, error) {
	if !e.Valid {
		return []byte{}, nil
	}
	return []byte(e.Val), nil
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (e *NullCrisisStatus) UnmarshalText(text []byte) error {
	if text == nil || len(text) == 0 {
		e.Valid = false
		return nil
	}

	e.Val = CrisisStatus(text)
	e.Valid = true
	return nil
}

// SetValid changes this NullCrisisStatus value and also sets it to be non-null.
func (e *NullCrisisStatus) SetValid(v CrisisStatus) {
	e.Val = v
	e.Valid = true
}

// Ptr returns a pointer to this NullCrisisStatus value, or a nil pointer if this NullCrisisStatus is null.
func (e NullCrisisStatus) Ptr() *CrisisStatus {
	if !e.Valid {
		return nil
	}
	return &e.Val
}

// IsZero returns true for null types.
func (e NullCrisisStatus) IsZero() bool {
	return !e.Valid
}

// Scan implements the Scanner interface.
func (e *NullCrisisStatus) Scan(value any) error {
	if value == nil {
		e.Val, e.Valid = "", false
		return nil
	}
	e.Valid = true
	return convert.ConvertAssign((*string)(&e.Val), value)
}

// Value implements the driver Valuer interface.
func (e NullCrisisStatus) Value() (driver.Value, error) {
	if !e.Valid {
		return nil, nil
	}
	return string(e.Val), nil
}
