// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package sqlboiler

var TableNames = struct {
	Campaigns            string
	Projects             string
	ProjectsCrisisConfig string
}{
	Campaigns:            "campaigns",
	Projects:             "projects",
	ProjectsCrisisConfig: "projects_crisis_config",
}
