// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package sqlboiler

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// ProjectsCrisisConfig is an object representing the database table.
type ProjectsCrisisConfig struct {
	ProjectID       string           `boil:"project_id" json:"project_id" toml:"project_id" yaml:"project_id"`
	Status          NullCrisisStatus `boil:"status" json:"status,omitempty" toml:"status" yaml:"status,omitempty"`
	KeywordsRules   null.JSON        `boil:"keywords_rules" json:"keywords_rules,omitempty" toml:"keywords_rules" yaml:"keywords_rules,omitempty"`
	VolumeRules     null.JSON        `boil:"volume_rules" json:"volume_rules,omitempty" toml:"volume_rules" yaml:"volume_rules,omitempty"`
	SentimentRules  null.JSON        `boil:"sentiment_rules" json:"sentiment_rules,omitempty" toml:"sentiment_rules" yaml:"sentiment_rules,omitempty"`
	InfluencerRules null.JSON        `boil:"influencer_rules" json:"influencer_rules,omitempty" toml:"influencer_rules" yaml:"influencer_rules,omitempty"`
	CreatedAt       null.Time        `boil:"created_at" json:"created_at,omitempty" toml:"created_at" yaml:"created_at,omitempty"`
	UpdatedAt       null.Time        `boil:"updated_at" json:"updated_at,omitempty" toml:"updated_at" yaml:"updated_at,omitempty"`

	R *projectsCrisisConfigR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L projectsCrisisConfigL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var ProjectsCrisisConfigColumns = struct {
	ProjectID       string
	Status          string
	KeywordsRules   string
	VolumeRules     string
	SentimentRules  string
	InfluencerRules string
	CreatedAt       string
	UpdatedAt       string
}{
	ProjectID:       "project_id",
	Status:          "status",
	KeywordsRules:   "keywords_rules",
	VolumeRules:     "volume_rules",
	SentimentRules:  "sentiment_rules",
	InfluencerRules: "influencer_rules",
	CreatedAt:       "created_at",
	UpdatedAt:       "updated_at",
}

var ProjectsCrisisConfigTableColumns = struct {
	ProjectID       string
	Status          string
	KeywordsRules   string
	VolumeRules     string
	SentimentRules  string
	InfluencerRules string
	CreatedAt       string
	UpdatedAt       string
}{
	ProjectID:       "projects_crisis_config.project_id",
	Status:          "projects_crisis_config.status",
	KeywordsRules:   "projects_crisis_config.keywords_rules",
	VolumeRules:     "projects_crisis_config.volume_rules",
	SentimentRules:  "projects_crisis_config.sentiment_rules",
	InfluencerRules: "projects_crisis_config.influencer_rules",
	CreatedAt:       "projects_crisis_config.created_at",
	UpdatedAt:       "projects_crisis_config.updated_at",
}

// Generated where

type whereHelperNullCrisisStatus struct{ field string }

func (w whereHelperNullCrisisStatus) EQ(x NullCrisisStatus) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, false, x)
}
func (w whereHelperNullCrisisStatus) NEQ(x NullCrisisStatus) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, true, x)
}
func (w whereHelperNullCrisisStatus) LT(x NullCrisisStatus) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelperNullCrisisStatus) LTE(x NullCrisisStatus) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelperNullCrisisStatus) GT(x NullCrisisStatus) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelperNullCrisisStatus) GTE(x NullCrisisStatus) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}
func (w whereHelperNullCrisisStatus) IN(slice []NullCrisisStatus) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperNullCrisisStatus) NIN(slice []NullCrisisStatus) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

func (w whereHelperNullCrisisStatus) IsNull() qm.QueryMod    { return qmhelper.WhereIsNull(w.field) }
func (w whereHelperNullCrisisStatus) IsNotNull() qm.QueryMod { return qmhelper.WhereIsNotNull(w.field) }

type whereHelpernull_JSON struct{ field string }

func (w whereHelpernull_JSON) EQ(x null.JSON) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, false, x)
}
func (w whereHelpernull_JSON) NEQ(x null.JSON) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, true, x)
}
func (w whereHelpernull_JSON) LT(x null.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpernull_JSON) LTE(x null.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpernull_JSON) GT(x null.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpernull_JSON) GTE(x null.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}

func (w whereHelpernull_JSON) IsNull() qm.QueryMod    { return qmhelper.WhereIsNull(w.field) }
func (w whereHelpernull_JSON) IsNotNull() qm.QueryMod { return qmhelper.WhereIsNotNull(w.field) }

var ProjectsCrisisConfigWhere = struct {
	ProjectID       whereHelperstring
	Status          whereHelperNullCrisisStatus
	KeywordsRules   whereHelpernull_JSON
	VolumeRules     whereHelpernull_JSON
	SentimentRules  whereHelpernull_JSON
	InfluencerRules whereHelpernull_JSON
	CreatedAt       whereHelpernull_Time
	UpdatedAt       whereHelpernull_Time
}{
	ProjectID:       whereHelperstring{field: "\"project\".\"projects_crisis_config\".\"project_id\""},
	Status:          whereHelperNullCrisisStatus{field: "\"project\".\"projects_crisis_config\".\"status\""},
	KeywordsRules:   whereHelpernull_JSON{field: "\"project\".\"projects_crisis_config\".\"keywords_rules\""},
	VolumeRules:     whereHelpernull_JSON{field: "\"project\".\"projects_crisis_config\".\"volume_rules\""},
	SentimentRules:  whereHelpernull_JSON{field: "\"project\".\"projects_crisis_config\".\"sentiment_rules\""},
	InfluencerRules: whereHelpernull_JSON{field: "\"project\".\"projects_crisis_config\".\"influencer_rules\""},
	CreatedAt:       whereHelpernull_Time{field: "\"project\".\"projects_crisis_config\".\"created_at\""},
	UpdatedAt:       whereHelpernull_Time{field: "\"project\".\"projects_crisis_config\".\"updated_at\""},
}

// ProjectsCrisisConfigRels is where relationship names are stored.
var ProjectsCrisisConfigRels = struct {
	Project string
}{
	Project: "Project",
}

// projectsCrisisConfigR is where relationships are stored.
type projectsCrisisConfigR struct {
	Project *Project `boil:"Project" json:"Project" toml:"Project" yaml:"Project"`
}

// NewStruct creates a new relationship struct
func (*projectsCrisisConfigR) NewStruct() *projectsCrisisConfigR {
	return &projectsCrisisConfigR{}
}

func (o *ProjectsCrisisConfig) GetProject() *Project {
	if o == nil {
		return nil
	}

	return o.R.GetProject()
}

func (r *projectsCrisisConfigR) GetProject() *Project {
	if r == nil {
		return nil
	}

	return r.Project
}

// projectsCrisisConfigL is where Load methods for each relationship are stored.
type projectsCrisisConfigL struct{}

var (
	projectsCrisisConfigAllColumns            = []string{"project_id", "status", "keywords_rules", "volume_rules", "sentiment_rules", "influencer_rules", "created_at", "updated_at"}
	projectsCrisisConfigColumnsWithoutDefault = []string{"project_id"}
	projectsCrisisConfigColumnsWithDefault    = []string{"status", "keywords_rules", "volume_rules", "sentiment_rules", "influencer_rules", "created_at", "updated_at"}
	projectsCrisisConfigPrimaryKeyColumns     = []string{"project_id"}
	projectsCrisisConfigGeneratedColumns      = []string{}
)

type (
	// ProjectsCrisisConfigSlice is an alias for a slice of pointers to ProjectsCrisisConfig.
	// This should almost always be used instead of []ProjectsCrisisConfig.
	ProjectsCrisisConfigSlice []*ProjectsCrisisConfig
	// ProjectsCrisisConfigHook is the signature for custom ProjectsCrisisConfig hook methods
	ProjectsCrisisConfigHook func(context.Context, boil.ContextExecutor, *ProjectsCrisisConfig) error

	projectsCrisisConfigQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	projectsCrisisConfigType                 = reflect.TypeOf(&ProjectsCrisisConfig{})
	projectsCrisisConfigMapping              = queries.MakeStructMapping(projectsCrisisConfigType)
	projectsCrisisConfigPrimaryKeyMapping, _ = queries.BindMapping(projectsCrisisConfigType, projectsCrisisConfigMapping, projectsCrisisConfigPrimaryKeyColumns)
	projectsCrisisConfigInsertCacheMut       sync.RWMutex
	projectsCrisisConfigInsertCache          = make(map[string]insertCache)
	projectsCrisisConfigUpdateCacheMut       sync.RWMutex
	projectsCrisisConfigUpdateCache          = make(map[string]updateCache)
	projectsCrisisConfigUpsertCacheMut       sync.RWMutex
	projectsCrisisConfigUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var projectsCrisisConfigAfterSelectMu sync.Mutex
var projectsCrisisConfigAfterSelectHooks []ProjectsCrisisConfigHook

var projectsCrisisConfigBeforeInsertMu sync.Mutex
var projectsCrisisConfigBeforeInsertHooks []ProjectsCrisisConfigHook
var projectsCrisisConfigAfterInsertMu sync.Mutex
var projectsCrisisConfigAfterInsertHooks []ProjectsCrisisConfigHook

var projectsCrisisConfigBeforeUpdateMu sync.Mutex
var projectsCrisisConfigBeforeUpdateHooks []ProjectsCrisisConfigHook
var projectsCrisisConfigAfterUpdateMu sync.Mutex
var projectsCrisisConfigAfterUpdateHooks []ProjectsCrisisConfigHook

var projectsCrisisConfigBeforeDeleteMu sync.Mutex
var projectsCrisisConfigBeforeDeleteHooks []ProjectsCrisisConfigHook
var projectsCrisisConfigAfterDeleteMu sync.Mutex
var projectsCrisisConfigAfterDeleteHooks []ProjectsCrisisConfigHook

var projectsCrisisConfigBeforeUpsertMu sync.Mutex
var projectsCrisisConfigBeforeUpsertHooks []ProjectsCrisisConfigHook
var projectsCrisisConfigAfterUpsertMu sync.Mutex
var projectsCrisisConfigAfterUpsertHooks []ProjectsCrisisConfigHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *ProjectsCrisisConfig) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range projectsCrisisConfigAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *ProjectsCrisisConfig) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range projectsCrisisConfigBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *ProjectsCrisisConfig) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range projectsCrisisConfigAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *ProjectsCrisisConfig) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range projectsCrisisConfigBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *ProjectsCrisisConfig) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range projectsCrisisConfigAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *ProjectsCrisisConfig) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range projectsCrisisConfigBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *ProjectsCrisisConfig) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range projectsCrisisConfigAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *ProjectsCrisisConfig) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range projectsCrisisConfigBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *ProjectsCrisisConfig) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range projectsCrisisConfigAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddProjectsCrisisConfigHook registers your hook function for all future operations.
func AddProjectsCrisisConfigHook(hookPoint boil.HookPoint, projectsCrisisConfigHook ProjectsCrisisConfigHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		projectsCrisisConfigAfterSelectMu.Lock()
		projectsCrisisConfigAfterSelectHooks = append(projectsCrisisConfigAfterSelectHooks, projectsCrisisConfigHook)
		projectsCrisisConfigAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		projectsCrisisConfigBeforeInsertMu.Lock()
		projectsCrisisConfigBeforeInsertHooks = append(projectsCrisisConfigBeforeInsertHooks, projectsCrisisConfigHook)
		projectsCrisisConfigBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		projectsCrisisConfigAfterInsertMu.Lock()
		projectsCrisisConfigAfterInsertHooks = append(projectsCrisisConfigAfterInsertHooks, projectsCrisisConfigHook)
		projectsCrisisConfigAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		projectsCrisisConfigBeforeUpdateMu.Lock()
		projectsCrisisConfigBeforeUpdateHooks = append(projectsCrisisConfigBeforeUpdateHooks, projectsCrisisConfigHook)
		projectsCrisisConfigBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		projectsCrisisConfigAfterUpdateMu.Lock()
		projectsCrisisConfigAfterUpdateHooks = append(projectsCrisisConfigAfterUpdateHooks, projectsCrisisConfigHook)
		projectsCrisisConfigAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		projectsCrisisConfigBeforeDeleteMu.Lock()
		projectsCrisisConfigBeforeDeleteHooks = append(projectsCrisisConfigBeforeDeleteHooks, projectsCrisisConfigHook)
		projectsCrisisConfigBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		projectsCrisisConfigAfterDeleteMu.Lock()
		projectsCrisisConfigAfterDeleteHooks = append(projectsCrisisConfigAfterDeleteHooks, projectsCrisisConfigHook)
		projectsCrisisConfigAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		projectsCrisisConfigBeforeUpsertMu.Lock()
		projectsCrisisConfigBeforeUpsertHooks = append(projectsCrisisConfigBeforeUpsertHooks, projectsCrisisConfigHook)
		projectsCrisisConfigBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		projectsCrisisConfigAfterUpsertMu.Lock()
		projectsCrisisConfigAfterUpsertHooks = append(projectsCrisisConfigAfterUpsertHooks, projectsCrisisConfigHook)
		projectsCrisisConfigAfterUpsertMu.Unlock()
	}
}

// One returns a single projectsCrisisConfig record from the query.
func (q projectsCrisisConfigQuery) One(ctx context.Context, exec boil.ContextExecutor) (*ProjectsCrisisConfig, error) {
	o := &ProjectsCrisisConfig{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "sqlboiler: failed to execute a one query for projects_crisis_config")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all ProjectsCrisisConfig records from the query.
func (q projectsCrisisConfigQuery) All(ctx context.Context, exec boil.ContextExecutor) (ProjectsCrisisConfigSlice, error) {
	var o []*ProjectsCrisisConfig

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "sqlboiler: failed to assign all query results to ProjectsCrisisConfig slice")
	}

	if len(projectsCrisisConfigAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all ProjectsCrisisConfig records in the query.
func (q projectsCrisisConfigQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: failed to count projects_crisis_config rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q projectsCrisisConfigQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "sqlboiler: failed to check if projects_crisis_config exists")
	}

	return count > 0, nil
}

// Project pointed to by the foreign key.
func (o *ProjectsCrisisConfig) Project(mods ...qm.QueryMod) projectQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.ProjectID),
	}

	queryMods = append(queryMods, mods...)

	return Projects(queryMods...)
}

// LoadProject allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (projectsCrisisConfigL) LoadProject(ctx context.Context, e boil.ContextExecutor, singular bool, maybeProjectsCrisisConfig any, mods queries.Applicator) error {
	var slice []*ProjectsCrisisConfig
	var object *ProjectsCrisisConfig

	if singular {
		var ok bool
		object, ok = maybeProjectsCrisisConfig.(*ProjectsCrisisConfig)
		if !ok {
			object = new(ProjectsCrisisConfig)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeProjectsCrisisConfig)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeProjectsCrisisConfig))
			}
		}
	} else {
		s, ok := maybeProjectsCrisisConfig.(*[]*ProjectsCrisisConfig)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeProjectsCrisisConfig)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeProjectsCrisisConfig))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &projectsCrisisConfigR{}
		}
		args[object.ProjectID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &projectsCrisisConfigR{}
			}

			args[obj.ProjectID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`project.projects`),
		qm.WhereIn(`project.projects.id in ?`, argsSlice...),
		qmhelper.WhereIsNull(`project.projects.deleted_at`),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Project")
	}

	var resultSlice []*Project
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Project")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for projects")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for projects")
	}

	if len(projectAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Project = foreign
		if foreign.R == nil {
			foreign.R = &projectR{}
		}
		foreign.R.ProjectsCrisisConfig = object
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.ProjectID == foreign.ID {
				local.R.Project = foreign
				if foreign.R == nil {
					foreign.R = &projectR{}
				}
				foreign.R.ProjectsCrisisConfig = local
				break
			}
		}
	}

	return nil
}

// SetProject of the projectsCrisisConfig to the related item.
// Sets o.R.Project to related.
// Adds o to related.R.ProjectsCrisisConfig.
func (o *ProjectsCrisisConfig) SetProject(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Project) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"project\".\"projects_crisis_config\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"project_id"}),
		strmangle.WhereClause("\"", "\"", 2, projectsCrisisConfigPrimaryKeyColumns),
	)
	values := []any{related.ID, o.ProjectID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.ProjectID = related.ID
	if o.R == nil {
		o.R = &projectsCrisisConfigR{
			Project: related,
		}
	} else {
		o.R.Project = related
	}

	if related.R == nil {
		related.R = &projectR{
			ProjectsCrisisConfig: o,
		}
	} else {
		related.R.ProjectsCrisisConfig = o
	}

	return nil
}

// ProjectsCrisisConfigs retrieves all the records using an executor.
func ProjectsCrisisConfigs(mods ...qm.QueryMod) projectsCrisisConfigQuery {
	mods = append(mods, qm.From("\"project\".\"projects_crisis_config\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"project\".\"projects_crisis_config\".*"})
	}

	return projectsCrisisConfigQuery{q}
}

// FindProjectsCrisisConfig retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindProjectsCrisisConfig(ctx context.Context, exec boil.ContextExecutor, projectID string, selectCols ...string) (*ProjectsCrisisConfig, error) {
	projectsCrisisConfigObj := &ProjectsCrisisConfig{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"project\".\"projects_crisis_config\" where \"project_id\"=$1", sel,
	)

	q := queries.Raw(query, projectID)

	err := q.Bind(ctx, exec, projectsCrisisConfigObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "sqlboiler: unable to select from projects_crisis_config")
	}

	if err = projectsCrisisConfigObj.doAfterSelectHooks(ctx, exec); err != nil {
		return projectsCrisisConfigObj, err
	}

	return projectsCrisisConfigObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *ProjectsCrisisConfig) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("sqlboiler: no projects_crisis_config provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if queries.MustTime(o.CreatedAt).IsZero() {
			queries.SetScanner(&o.CreatedAt, currTime)
		}
		if queries.MustTime(o.UpdatedAt).IsZero() {
			queries.SetScanner(&o.UpdatedAt, currTime)
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(projectsCrisisConfigColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	projectsCrisisConfigInsertCacheMut.RLock()
	cache, cached := projectsCrisisConfigInsertCache[key]
	projectsCrisisConfigInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			projectsCrisisConfigAllColumns,
			projectsCrisisConfigColumnsWithDefault,
			projectsCrisisConfigColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(projectsCrisisConfigType, projectsCrisisConfigMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(projectsCrisisConfigType, projectsCrisisConfigMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"project\".\"projects_crisis_config\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"project\".\"projects_crisis_config\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "sqlboiler: unable to insert into projects_crisis_config")
	}

	if !cached {
		projectsCrisisConfigInsertCacheMut.Lock()
		projectsCrisisConfigInsertCache[key] = cache
		projectsCrisisConfigInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the ProjectsCrisisConfig.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *ProjectsCrisisConfig) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		queries.SetScanner(&o.UpdatedAt, currTime)
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	projectsCrisisConfigUpdateCacheMut.RLock()
	cache, cached := projectsCrisisConfigUpdateCache[key]
	projectsCrisisConfigUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			projectsCrisisConfigAllColumns,
			projectsCrisisConfigPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("sqlboiler: unable to update projects_crisis_config, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"project\".\"projects_crisis_config\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, projectsCrisisConfigPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(projectsCrisisConfigType, projectsCrisisConfigMapping, append(wl, projectsCrisisConfigPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to update projects_crisis_config row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: failed to get rows affected by update for projects_crisis_config")
	}

	if !cached {
		projectsCrisisConfigUpdateCacheMut.Lock()
		projectsCrisisConfigUpdateCache[key] = cache
		projectsCrisisConfigUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q projectsCrisisConfigQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to update all for projects_crisis_config")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to retrieve rows affected for projects_crisis_config")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o ProjectsCrisisConfigSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("sqlboiler: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]any, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), projectsCrisisConfigPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"project\".\"projects_crisis_config\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, projectsCrisisConfigPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to update all in projectsCrisisConfig slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to retrieve rows affected all in update all projectsCrisisConfig")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *ProjectsCrisisConfig) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("sqlboiler: no projects_crisis_config provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if queries.MustTime(o.CreatedAt).IsZero() {
			queries.SetScanner(&o.CreatedAt, currTime)
		}
		queries.SetScanner(&o.UpdatedAt, currTime)
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(projectsCrisisConfigColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	projectsCrisisConfigUpsertCacheMut.RLock()
	cache, cached := projectsCrisisConfigUpsertCache[key]
	projectsCrisisConfigUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			projectsCrisisConfigAllColumns,
			projectsCrisisConfigColumnsWithDefault,
			projectsCrisisConfigColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			projectsCrisisConfigAllColumns,
			projectsCrisisConfigPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("sqlboiler: unable to upsert projects_crisis_config, could not build update column list")
		}

		ret := strmangle.SetComplement(projectsCrisisConfigAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(projectsCrisisConfigPrimaryKeyColumns) == 0 {
				return errors.New("sqlboiler: unable to upsert projects_crisis_config, could not build conflict column list")
			}

			conflict = make([]string, len(projectsCrisisConfigPrimaryKeyColumns))
			copy(conflict, projectsCrisisConfigPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"project\".\"projects_crisis_config\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(projectsCrisisConfigType, projectsCrisisConfigMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(projectsCrisisConfigType, projectsCrisisConfigMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []any
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "sqlboiler: unable to upsert projects_crisis_config")
	}

	if !cached {
		projectsCrisisConfigUpsertCacheMut.Lock()
		projectsCrisisConfigUpsertCache[key] = cache
		projectsCrisisConfigUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single ProjectsCrisisConfig record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *ProjectsCrisisConfig) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("sqlboiler: no ProjectsCrisisConfig provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), projectsCrisisConfigPrimaryKeyMapping)
	sql := "DELETE FROM \"project\".\"projects_crisis_config\" WHERE \"project_id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to delete from projects_crisis_config")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: failed to get rows affected by delete for projects_crisis_config")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q projectsCrisisConfigQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("sqlboiler: no projectsCrisisConfigQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to delete all from projects_crisis_config")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: failed to get rows affected by deleteall for projects_crisis_config")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o ProjectsCrisisConfigSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(projectsCrisisConfigBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []any
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), projectsCrisisConfigPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"project\".\"projects_crisis_config\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, projectsCrisisConfigPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to delete all from projectsCrisisConfig slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: failed to get rows affected by deleteall for projects_crisis_config")
	}

	if len(projectsCrisisConfigAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *ProjectsCrisisConfig) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindProjectsCrisisConfig(ctx, exec, o.ProjectID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *ProjectsCrisisConfigSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := ProjectsCrisisConfigSlice{}
	var args []any
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), projectsCrisisConfigPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"project\".\"projects_crisis_config\".* FROM \"project\".\"projects_crisis_config\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, projectsCrisisConfigPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "sqlboiler: unable to reload all in ProjectsCrisisConfigSlice")
	}

	*o = slice

	return nil
}

// ProjectsCrisisConfigExists checks if the ProjectsCrisisConfig row exists.
func ProjectsCrisisConfigExists(ctx context.Context, exec boil.ContextExecutor, projectID string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"project\".\"projects_crisis_config\" where \"project_id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, projectID)
	}
	row := exec.QueryRowContext(ctx, sql, projectID)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "sqlboiler: unable to check if projects_crisis_config exists")
	}

	return exists, nil
}

// Exists checks if the ProjectsCrisisConfig row exists.
func (o *ProjectsCrisisConfig) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return ProjectsCrisisConfigExists(ctx, exec, o.ProjectID)
}
