// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package sqlboiler

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/sqlboiler/v4/types"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// Project is an object representing the database table.
type Project struct {
	ID              string                  `boil:"id" json:"id" toml:"id" yaml:"id"`
	CampaignID      string                  `boil:"campaign_id" json:"campaign_id" toml:"campaign_id" yaml:"campaign_id"`
	Name            string                  `boil:"name" json:"name" toml:"name" yaml:"name"`
	Description     null.String             `boil:"description" json:"description,omitempty" toml:"description" yaml:"description,omitempty"`
	Brand           null.String             `boil:"brand" json:"brand,omitempty" toml:"brand" yaml:"brand,omitempty"`
	EntityType      EntityType              `boil:"entity_type" json:"entity_type" toml:"entity_type" yaml:"entity_type"`
	EntityName      string                  `boil:"entity_name" json:"entity_name" toml:"entity_name" yaml:"entity_name"`
	DomainTypeCode  string                  `boil:"domain_type_code" json:"domain_type_code" toml:"domain_type_code" yaml:"domain_type_code"`
	Status          ProjectStatus           `boil:"status" json:"status" toml:"status" yaml:"status"`
	ConfigStatus    NullProjectConfigStatus `boil:"config_status" json:"config_status,omitempty" toml:"config_status" yaml:"config_status,omitempty"`
	CreatedBy       string                  `boil:"created_by" json:"created_by" toml:"created_by" yaml:"created_by"`
	FavoriteUserIds types.StringArray       `boil:"favorite_user_ids" json:"favorite_user_ids" toml:"favorite_user_ids" yaml:"favorite_user_ids"`
	CreatedAt       null.Time               `boil:"created_at" json:"created_at,omitempty" toml:"created_at" yaml:"created_at,omitempty"`
	UpdatedAt       null.Time               `boil:"updated_at" json:"updated_at,omitempty" toml:"updated_at" yaml:"updated_at,omitempty"`
	DeletedAt       null.Time               `boil:"deleted_at" json:"deleted_at,omitempty" toml:"deleted_at" yaml:"deleted_at,omitempty"`

	R *projectR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L projectL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var ProjectColumns = struct {
	ID              string
	CampaignID      string
	Name            string
	Description     string
	Brand           string
	EntityType      string
	EntityName      string
	DomainTypeCode  string
	Status          string
	ConfigStatus    string
	CreatedBy       string
	FavoriteUserIds string
	CreatedAt       string
	UpdatedAt       string
	DeletedAt       string
}{
	ID:              "id",
	CampaignID:      "campaign_id",
	Name:            "name",
	Description:     "description",
	Brand:           "brand",
	EntityType:      "entity_type",
	EntityName:      "entity_name",
	DomainTypeCode:  "domain_type_code",
	Status:          "status",
	ConfigStatus:    "config_status",
	CreatedBy:       "created_by",
	FavoriteUserIds: "favorite_user_ids",
	CreatedAt:       "created_at",
	UpdatedAt:       "updated_at",
	DeletedAt:       "deleted_at",
}

var ProjectTableColumns = struct {
	ID              string
	CampaignID      string
	Name            string
	Description     string
	Brand           string
	EntityType      string
	EntityName      string
	DomainTypeCode  string
	Status          string
	ConfigStatus    string
	CreatedBy       string
	FavoriteUserIds string
	CreatedAt       string
	UpdatedAt       string
	DeletedAt       string
}{
	ID:              "projects.id",
	CampaignID:      "projects.campaign_id",
	Name:            "projects.name",
	Description:     "projects.description",
	Brand:           "projects.brand",
	EntityType:      "projects.entity_type",
	EntityName:      "projects.entity_name",
	DomainTypeCode:  "projects.domain_type_code",
	Status:          "projects.status",
	ConfigStatus:    "projects.config_status",
	CreatedBy:       "projects.created_by",
	FavoriteUserIds: "projects.favorite_user_ids",
	CreatedAt:       "projects.created_at",
	UpdatedAt:       "projects.updated_at",
	DeletedAt:       "projects.deleted_at",
}

// Generated where

type whereHelperEntityType struct{ field string }

func (w whereHelperEntityType) EQ(x EntityType) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.EQ, x)
}
func (w whereHelperEntityType) NEQ(x EntityType) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.NEQ, x)
}
func (w whereHelperEntityType) LT(x EntityType) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelperEntityType) LTE(x EntityType) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelperEntityType) GT(x EntityType) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelperEntityType) GTE(x EntityType) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}
func (w whereHelperEntityType) IN(slice []EntityType) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperEntityType) NIN(slice []EntityType) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

type whereHelperProjectStatus struct{ field string }

func (w whereHelperProjectStatus) EQ(x ProjectStatus) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.EQ, x)
}
func (w whereHelperProjectStatus) NEQ(x ProjectStatus) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.NEQ, x)
}
func (w whereHelperProjectStatus) LT(x ProjectStatus) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelperProjectStatus) LTE(x ProjectStatus) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelperProjectStatus) GT(x ProjectStatus) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelperProjectStatus) GTE(x ProjectStatus) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}
func (w whereHelperProjectStatus) IN(slice []ProjectStatus) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperProjectStatus) NIN(slice []ProjectStatus) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

type whereHelperNullProjectConfigStatus struct{ field string }

func (w whereHelperNullProjectConfigStatus) EQ(x NullProjectConfigStatus) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, false, x)
}
func (w whereHelperNullProjectConfigStatus) NEQ(x NullProjectConfigStatus) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, true, x)
}
func (w whereHelperNullProjectConfigStatus) LT(x NullProjectConfigStatus) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelperNullProjectConfigStatus) LTE(x NullProjectConfigStatus) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelperNullProjectConfigStatus) GT(x NullProjectConfigStatus) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelperNullProjectConfigStatus) GTE(x NullProjectConfigStatus) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}
func (w whereHelperNullProjectConfigStatus) IN(slice []NullProjectConfigStatus) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperNullProjectConfigStatus) NIN(slice []NullProjectConfigStatus) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

func (w whereHelperNullProjectConfigStatus) IsNull() qm.QueryMod {
	return qmhelper.WhereIsNull(w.field)
}
func (w whereHelperNullProjectConfigStatus) IsNotNull() qm.QueryMod {
	return qmhelper.WhereIsNotNull(w.field)
}

var ProjectWhere = struct {
	ID              whereHelperstring
	CampaignID      whereHelperstring
	Name            whereHelperstring
	Description     whereHelpernull_String
	Brand           whereHelpernull_String
	EntityType      whereHelperEntityType
	EntityName      whereHelperstring
	DomainTypeCode  whereHelperstring
	Status          whereHelperProjectStatus
	ConfigStatus    whereHelperNullProjectConfigStatus
	CreatedBy       whereHelperstring
	FavoriteUserIds whereHelpertypes_StringArray
	CreatedAt       whereHelpernull_Time
	UpdatedAt       whereHelpernull_Time
	DeletedAt       whereHelpernull_Time
}{
	ID:              whereHelperstring{field: "\"project\".\"projects\".\"id\""},
	CampaignID:      whereHelperstring{field: "\"project\".\"projects\".\"campaign_id\""},
	Name:            whereHelperstring{field: "\"project\".\"projects\".\"name\""},
	Description:     whereHelpernull_String{field: "\"project\".\"projects\".\"description\""},
	Brand:           whereHelpernull_String{field: "\"project\".\"projects\".\"brand\""},
	EntityType:      whereHelperEntityType{field: "\"project\".\"projects\".\"entity_type\""},
	EntityName:      whereHelperstring{field: "\"project\".\"projects\".\"entity_name\""},
	DomainTypeCode:  whereHelperstring{field: "\"project\".\"projects\".\"domain_type_code\""},
	Status:          whereHelperProjectStatus{field: "\"project\".\"projects\".\"status\""},
	ConfigStatus:    whereHelperNullProjectConfigStatus{field: "\"project\".\"projects\".\"config_status\""},
	CreatedBy:       whereHelperstring{field: "\"project\".\"projects\".\"created_by\""},
	FavoriteUserIds: whereHelpertypes_StringArray{field: "\"project\".\"projects\".\"favorite_user_ids\""},
	CreatedAt:       whereHelpernull_Time{field: "\"project\".\"projects\".\"created_at\""},
	UpdatedAt:       whereHelpernull_Time{field: "\"project\".\"projects\".\"updated_at\""},
	DeletedAt:       whereHelpernull_Time{field: "\"project\".\"projects\".\"deleted_at\""},
}

// ProjectRels is where relationship names are stored.
var ProjectRels = struct {
	Campaign             string
	ProjectsCrisisConfig string
}{
	Campaign:             "Campaign",
	ProjectsCrisisConfig: "ProjectsCrisisConfig",
}

// projectR is where relationships are stored.
type projectR struct {
	Campaign             *Campaign             `boil:"Campaign" json:"Campaign" toml:"Campaign" yaml:"Campaign"`
	ProjectsCrisisConfig *ProjectsCrisisConfig `boil:"ProjectsCrisisConfig" json:"ProjectsCrisisConfig" toml:"ProjectsCrisisConfig" yaml:"ProjectsCrisisConfig"`
}

// NewStruct creates a new relationship struct
func (*projectR) NewStruct() *projectR {
	return &projectR{}
}

func (o *Project) GetCampaign() *Campaign {
	if o == nil {
		return nil
	}

	return o.R.GetCampaign()
}

func (r *projectR) GetCampaign() *Campaign {
	if r == nil {
		return nil
	}

	return r.Campaign
}

func (o *Project) GetProjectsCrisisConfig() *ProjectsCrisisConfig {
	if o == nil {
		return nil
	}

	return o.R.GetProjectsCrisisConfig()
}

func (r *projectR) GetProjectsCrisisConfig() *ProjectsCrisisConfig {
	if r == nil {
		return nil
	}

	return r.ProjectsCrisisConfig
}

// projectL is where Load methods for each relationship are stored.
type projectL struct{}

var (
	projectAllColumns            = []string{"id", "campaign_id", "name", "description", "brand", "entity_type", "entity_name", "domain_type_code", "status", "config_status", "created_by", "favorite_user_ids", "created_at", "updated_at", "deleted_at"}
	projectColumnsWithoutDefault = []string{"campaign_id", "name", "entity_name", "created_by"}
	projectColumnsWithDefault    = []string{"id", "description", "brand", "entity_type", "domain_type_code", "status", "config_status", "favorite_user_ids", "created_at", "updated_at", "deleted_at"}
	projectPrimaryKeyColumns     = []string{"id"}
	projectGeneratedColumns      = []string{}
)

type (
	// ProjectSlice is an alias for a slice of pointers to Project.
	// This should almost always be used instead of []Project.
	ProjectSlice []*Project
	// ProjectHook is the signature for custom Project hook methods
	ProjectHook func(context.Context, boil.ContextExecutor, *Project) error

	projectQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	projectType                 = reflect.TypeOf(&Project{})
	projectMapping              = queries.MakeStructMapping(projectType)
	projectPrimaryKeyMapping, _ = queries.BindMapping(projectType, projectMapping, projectPrimaryKeyColumns)
	projectInsertCacheMut       sync.RWMutex
	projectInsertCache          = make(map[string]insertCache)
	projectUpdateCacheMut       sync.RWMutex
	projectUpdateCache          = make(map[string]updateCache)
	projectUpsertCacheMut       sync.RWMutex
	projectUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var projectAfterSelectMu sync.Mutex
var projectAfterSelectHooks []ProjectHook

var projectBeforeInsertMu sync.Mutex
var projectBeforeInsertHooks []ProjectHook
var projectAfterInsertMu sync.Mutex
var projectAfterInsertHooks []ProjectHook

var projectBeforeUpdateMu sync.Mutex
var projectBeforeUpdateHooks []ProjectHook
var projectAfterUpdateMu sync.Mutex
var projectAfterUpdateHooks []ProjectHook

var projectBeforeDeleteMu sync.Mutex
var projectBeforeDeleteHooks []ProjectHook
var projectAfterDeleteMu sync.Mutex
var projectAfterDeleteHooks []ProjectHook

var projectBeforeUpsertMu sync.Mutex
var projectBeforeUpsertHooks []ProjectHook
var projectAfterUpsertMu sync.Mutex
var projectAfterUpsertHooks []ProjectHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *Project) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range projectAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *Project) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range projectBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *Project) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range projectAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *Project) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range projectBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *Project) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range projectAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *Project) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range projectBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *Project) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range projectAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *Project) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range projectBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *Project) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range projectAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddProjectHook registers your hook function for all future operations.
func AddProjectHook(hookPoint boil.HookPoint, projectHook ProjectHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		projectAfterSelectMu.Lock()
		projectAfterSelectHooks = append(projectAfterSelectHooks, projectHook)
		projectAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		projectBeforeInsertMu.Lock()
		projectBeforeInsertHooks = append(projectBeforeInsertHooks, projectHook)
		projectBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		projectAfterInsertMu.Lock()
		projectAfterInsertHooks = append(projectAfterInsertHooks, projectHook)
		projectAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		projectBeforeUpdateMu.Lock()
		projectBeforeUpdateHooks = append(projectBeforeUpdateHooks, projectHook)
		projectBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		projectAfterUpdateMu.Lock()
		projectAfterUpdateHooks = append(projectAfterUpdateHooks, projectHook)
		projectAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		projectBeforeDeleteMu.Lock()
		projectBeforeDeleteHooks = append(projectBeforeDeleteHooks, projectHook)
		projectBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		projectAfterDeleteMu.Lock()
		projectAfterDeleteHooks = append(projectAfterDeleteHooks, projectHook)
		projectAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		projectBeforeUpsertMu.Lock()
		projectBeforeUpsertHooks = append(projectBeforeUpsertHooks, projectHook)
		projectBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		projectAfterUpsertMu.Lock()
		projectAfterUpsertHooks = append(projectAfterUpsertHooks, projectHook)
		projectAfterUpsertMu.Unlock()
	}
}

// One returns a single project record from the query.
func (q projectQuery) One(ctx context.Context, exec boil.ContextExecutor) (*Project, error) {
	o := &Project{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "sqlboiler: failed to execute a one query for projects")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all Project records from the query.
func (q projectQuery) All(ctx context.Context, exec boil.ContextExecutor) (ProjectSlice, error) {
	var o []*Project

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "sqlboiler: failed to assign all query results to Project slice")
	}

	if len(projectAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all Project records in the query.
func (q projectQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: failed to count projects rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q projectQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "sqlboiler: failed to check if projects exists")
	}

	return count > 0, nil
}

// Campaign pointed to by the foreign key.
func (o *Project) Campaign(mods ...qm.QueryMod) campaignQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.CampaignID),
	}

	queryMods = append(queryMods, mods...)

	return Campaigns(queryMods...)
}

// ProjectsCrisisConfig pointed to by the foreign key.
func (o *Project) ProjectsCrisisConfig(mods ...qm.QueryMod) projectsCrisisConfigQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"project_id\" = ?", o.ID),
	}

	queryMods = append(queryMods, mods...)

	return ProjectsCrisisConfigs(queryMods...)
}

// LoadCampaign allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (projectL) LoadCampaign(ctx context.Context, e boil.ContextExecutor, singular bool, maybeProject any, mods queries.Applicator) error {
	var slice []*Project
	var object *Project

	if singular {
		var ok bool
		object, ok = maybeProject.(*Project)
		if !ok {
			object = new(Project)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeProject)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeProject))
			}
		}
	} else {
		s, ok := maybeProject.(*[]*Project)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeProject)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeProject))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &projectR{}
		}
		args[object.CampaignID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &projectR{}
			}

			args[obj.CampaignID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`project.campaigns`),
		qm.WhereIn(`project.campaigns.id in ?`, argsSlice...),
		qmhelper.WhereIsNull(`project.campaigns.deleted_at`),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Campaign")
	}

	var resultSlice []*Campaign
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Campaign")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for campaigns")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for campaigns")
	}

	if len(campaignAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Campaign = foreign
		if foreign.R == nil {
			foreign.R = &campaignR{}
		}
		foreign.R.Projects = append(foreign.R.Projects, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.CampaignID == foreign.ID {
				local.R.Campaign = foreign
				if foreign.R == nil {
					foreign.R = &campaignR{}
				}
				foreign.R.Projects = append(foreign.R.Projects, local)
				break
			}
		}
	}

	return nil
}

// LoadProjectsCrisisConfig allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-1 relationship.
func (projectL) LoadProjectsCrisisConfig(ctx context.Context, e boil.ContextExecutor, singular bool, maybeProject any, mods queries.Applicator) error {
	var slice []*Project
	var object *Project

	if singular {
		var ok bool
		object, ok = maybeProject.(*Project)
		if !ok {
			object = new(Project)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeProject)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeProject))
			}
		}
	} else {
		s, ok := maybeProject.(*[]*Project)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeProject)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeProject))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &projectR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &projectR{}
			}

			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`project.projects_crisis_config`),
		qm.WhereIn(`project.projects_crisis_config.project_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load ProjectsCrisisConfig")
	}

	var resultSlice []*ProjectsCrisisConfig
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice ProjectsCrisisConfig")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for projects_crisis_config")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for projects_crisis_config")
	}

	if len(projectsCrisisConfigAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.ProjectsCrisisConfig = foreign
		if foreign.R == nil {
			foreign.R = &projectsCrisisConfigR{}
		}
		foreign.R.Project = object
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.ID == foreign.ProjectID {
				local.R.ProjectsCrisisConfig = foreign
				if foreign.R == nil {
					foreign.R = &projectsCrisisConfigR{}
				}
				foreign.R.Project = local
				break
			}
		}
	}

	return nil
}

// SetCampaign of the project to the related item.
// Sets o.R.Campaign to related.
// Adds o to related.R.Projects.
func (o *Project) SetCampaign(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Campaign) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"project\".\"projects\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"campaign_id"}),
		strmangle.WhereClause("\"", "\"", 2, projectPrimaryKeyColumns),
	)
	values := []any{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.CampaignID = related.ID
	if o.R == nil {
		o.R = &projectR{
			Campaign: related,
		}
	} else {
		o.R.Campaign = related
	}

	if related.R == nil {
		related.R = &campaignR{
			Projects: ProjectSlice{o},
		}
	} else {
		related.R.Projects = append(related.R.Projects, o)
	}

	return nil
}

// SetProjectsCrisisConfig of the project to the related item.
// Sets o.R.ProjectsCrisisConfig to related.
// Adds o to related.R.Project.
func (o *Project) SetProjectsCrisisConfig(ctx context.Context, exec boil.ContextExecutor, insert bool, related *ProjectsCrisisConfig) error {
	var err error

	if insert {
		related.ProjectID = o.ID

		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	} else {
		updateQuery := fmt.Sprintf(
			"UPDATE \"project\".\"projects_crisis_config\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, []string{"project_id"}),
			strmangle.WhereClause("\"", "\"", 2, projectsCrisisConfigPrimaryKeyColumns),
		)
		values := []any{o.ID, related.ProjectID}

		if boil.IsDebug(ctx) {
			writer := boil.DebugWriterFrom(ctx)
			fmt.Fprintln(writer, updateQuery)
			fmt.Fprintln(writer, values)
		}
		if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
			return errors.Wrap(err, "failed to update foreign table")
		}

		related.ProjectID = o.ID
	}

	if o.R == nil {
		o.R = &projectR{
			ProjectsCrisisConfig: related,
		}
	} else {
		o.R.ProjectsCrisisConfig = related
	}

	if related.R == nil {
		related.R = &projectsCrisisConfigR{
			Project: o,
		}
	} else {
		related.R.Project = o
	}
	return nil
}

// Projects retrieves all the records using an executor.
func Projects(mods ...qm.QueryMod) projectQuery {
	mods = append(mods, qm.From("\"project\".\"projects\""), qmhelper.WhereIsNull("\"project\".\"projects\".\"deleted_at\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"project\".\"projects\".*"})
	}

	return projectQuery{q}
}

// FindProject retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindProject(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*Project, error) {
	projectObj := &Project{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"project\".\"projects\" where \"id\"=$1 and \"deleted_at\" is null", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, projectObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "sqlboiler: unable to select from projects")
	}

	if err = projectObj.doAfterSelectHooks(ctx, exec); err != nil {
		return projectObj, err
	}

	return projectObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *Project) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("sqlboiler: no projects provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if queries.MustTime(o.CreatedAt).IsZero() {
			queries.SetScanner(&o.CreatedAt, currTime)
		}
		if queries.MustTime(o.UpdatedAt).IsZero() {
			queries.SetScanner(&o.UpdatedAt, currTime)
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(projectColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	projectInsertCacheMut.RLock()
	cache, cached := projectInsertCache[key]
	projectInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			projectAllColumns,
			projectColumnsWithDefault,
			projectColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(projectType, projectMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(projectType, projectMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"project\".\"projects\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"project\".\"projects\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "sqlboiler: unable to insert into projects")
	}

	if !cached {
		projectInsertCacheMut.Lock()
		projectInsertCache[key] = cache
		projectInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the Project.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *Project) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		queries.SetScanner(&o.UpdatedAt, currTime)
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	projectUpdateCacheMut.RLock()
	cache, cached := projectUpdateCache[key]
	projectUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			projectAllColumns,
			projectPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("sqlboiler: unable to update projects, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"project\".\"projects\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, projectPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(projectType, projectMapping, append(wl, projectPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to update projects row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: failed to get rows affected by update for projects")
	}

	if !cached {
		projectUpdateCacheMut.Lock()
		projectUpdateCache[key] = cache
		projectUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q projectQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to update all for projects")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to retrieve rows affected for projects")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o ProjectSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("sqlboiler: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]any, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), projectPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"project\".\"projects\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, projectPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to update all in project slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to retrieve rows affected all in update all project")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *Project) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("sqlboiler: no projects provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if queries.MustTime(o.CreatedAt).IsZero() {
			queries.SetScanner(&o.CreatedAt, currTime)
		}
		queries.SetScanner(&o.UpdatedAt, currTime)
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(projectColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	projectUpsertCacheMut.RLock()
	cache, cached := projectUpsertCache[key]
	projectUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			projectAllColumns,
			projectColumnsWithDefault,
			projectColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			projectAllColumns,
			projectPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("sqlboiler: unable to upsert projects, could not build update column list")
		}

		ret := strmangle.SetComplement(projectAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(projectPrimaryKeyColumns) == 0 {
				return errors.New("sqlboiler: unable to upsert projects, could not build conflict column list")
			}

			conflict = make([]string, len(projectPrimaryKeyColumns))
			copy(conflict, projectPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"project\".\"projects\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(projectType, projectMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(projectType, projectMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []any
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "sqlboiler: unable to upsert projects")
	}

	if !cached {
		projectUpsertCacheMut.Lock()
		projectUpsertCache[key] = cache
		projectUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single Project record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Project) Delete(ctx context.Context, exec boil.ContextExecutor, hardDelete bool) (int64, error) {
	if o == nil {
		return 0, errors.New("sqlboiler: no Project provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	var (
		sql  string
		args []any
	)
	if hardDelete {
		args = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), projectPrimaryKeyMapping)
		sql = "DELETE FROM \"project\".\"projects\" WHERE \"id\"=$1"
	} else {
		currTime := time.Now().In(boil.GetLocation())
		o.DeletedAt = null.TimeFrom(currTime)
		wl := []string{"deleted_at"}
		sql = fmt.Sprintf("UPDATE \"project\".\"projects\" SET %s WHERE \"id\"=$2",
			strmangle.SetParamNames("\"", "\"", 1, wl),
		)
		valueMapping, err := queries.BindMapping(projectType, projectMapping, append(wl, projectPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
		args = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), valueMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to delete from projects")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: failed to get rows affected by delete for projects")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q projectQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor, hardDelete bool) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("sqlboiler: no projectQuery provided for delete all")
	}

	if hardDelete {
		queries.SetDelete(q.Query)
	} else {
		currTime := time.Now().In(boil.GetLocation())
		queries.SetUpdate(q.Query, M{"deleted_at": currTime})
	}

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to delete all from projects")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: failed to get rows affected by deleteall for projects")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o ProjectSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor, hardDelete bool) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(projectBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var (
		sql  string
		args []any
	)
	if hardDelete {
		for _, obj := range o {
			pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), projectPrimaryKeyMapping)
			args = append(args, pkeyArgs...)
		}
		sql = "DELETE FROM \"project\".\"projects\" WHERE " +
			strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, projectPrimaryKeyColumns, len(o))
	} else {
		currTime := time.Now().In(boil.GetLocation())
		for _, obj := range o {
			pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), projectPrimaryKeyMapping)
			args = append(args, pkeyArgs...)
			obj.DeletedAt = null.TimeFrom(currTime)
		}
		wl := []string{"deleted_at"}
		sql = fmt.Sprintf("UPDATE \"project\".\"projects\" SET %s WHERE "+
			strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 2, projectPrimaryKeyColumns, len(o)),
			strmangle.SetParamNames("\"", "\"", 1, wl),
		)
		args = append([]any{currTime}, args...)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to delete all from project slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: failed to get rows affected by deleteall for projects")
	}

	if len(projectAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Project) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindProject(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *ProjectSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := ProjectSlice{}
	var args []any
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), projectPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"project\".\"projects\".* FROM \"project\".\"projects\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, projectPrimaryKeyColumns, len(*o)) +
		"and \"deleted_at\" is null"

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "sqlboiler: unable to reload all in ProjectSlice")
	}

	*o = slice

	return nil
}

// ProjectExists checks if the Project row exists.
func ProjectExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"project\".\"projects\" where \"id\"=$1 and \"deleted_at\" is null limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "sqlboiler: unable to check if projects exists")
	}

	return exists, nil
}

// Exists checks if the Project row exists.
func (o *Project) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return ProjectExists(ctx, exec, o.ID)
}
